from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

if not GetDepend('USING_BATTERY_CALCULATOR'):
    SrcRemove(src, 'battery_table.c')

path =  [os.path.join(cwd, ".")]

group = DefineGroup('Drivers', src, depend = [], CPPPATH = path)

Return('group')
