from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB52_XIAOZHI_M'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB52_XIAOZHI_M'):
    group = group + SConscript(os.path.join(cwd, '../sf32lb52-xiaozhi-M_base/SConscript'), variant_dir="base", duplicate=0)

Return('group')
