# for module compiling
import os
from building import *
import rtconfig

cwd = GetCurrentDir()
list = os.listdir(cwd)
objs = []
objs_ezip = []

objs_ezip += Glob('*.png')
objs_ezip += Glob('./angry/*.png')
objs_ezip += Glob('./confident/*.png')
objs_ezip += Glob('./confused/*.png')
objs_ezip += Glob('./cool/*.png')
objs_ezip += Glob('./crying/*.png')
objs_ezip += Glob('./delicious/*.png')
objs_ezip += Glob('./embarrassed/*.png')
objs_ezip += Glob('./funny/*.png')
objs_ezip += Glob('./happy/*.png')
objs_ezip += Glob('./kissy/*.png')
objs_ezip += Glob('./laughing/*.png')
objs_ezip += Glob('./loving/*.png')
objs_ezip += Glob('./neutral/*.png')
objs_ezip += Glob('./relaxed/*.png')
objs_ezip += Glob('./sad/*.png')
objs_ezip += Glob('./shocked/*.png')
objs_ezip += Glob('./silly/*.png')
objs_ezip += Glob('./sleepy/*.png')
objs_ezip += Glob('./surprised/*.png')
objs_ezip += Glob('./thinking/*.png')
objs_ezip += Glob('./winking/*.png')
objs_ezip += Glob('./time/*.png')
objs_ezip += Glob('./weather/*.png')
def align_to_power_of_two_and_str(num):
    power = 1
    while power < num:
        power *= 2
    return str(power)

#color_fmt, file_fmt, section_name
if 16 == GetConfigValue('LV_COLOR_DEPTH'):
    img_flags = '-rgb565'
else:
    img_flags = '-rgb888'

img_flags = img_flags + ' -lvgl_version 9 '

if GetDepend('EZIP_PAL_SUPPORT'):
    if GetDepend('EZIP_PAL_SUPPORT_1'):
        img_flags += ' -pal_support 1 '
    else:
        img_flags += ' -pal_support '

if GetDepend('LV_FB_LINE_NUM'):
    ers_v = align_to_power_of_two_and_str(GetConfigValue('LV_FB_LINE_NUM'))
else:
    ers_v = '128'


# Check if EZIP_BINARY_MODE macro is defined
if GetDepend('EZIP_BINARY_MODE'):
    # Generate ezip binary files to current directory (which is the build directory due to variant_dir)
    objs += Env.ImgResource(objs_ezip, img_flags+' -binfile 2 -binext .ezip -dpt 1 -detailcf 16')
else:
    # Default: generate C files (original behavior)
    objs += Env.ImgResource(objs_ezip, img_flags+' -section ROM3_IMG -cfile 2 -dpt 1')


if GetOption('no_cc'):
    objs = []
    
objs = DefineGroup('resource', objs, depend = ['PKG_USING_LITTLEVGL2RTT'])  

Return ('objs')

